### ISSUE TITLE
TODO V2

### ISSUE THREAD

**Issue by yoannfleurydev** [Fork-It-Community/forkit.community#175]
<details>
<summary>SEO (done ✅)</summary>

- [x] title, description
  - [x] event
  - [x] talk
  - [x] homepage
  - [x] event list
  - [x] "static page"
    - [x] CoC
    - [x] about
  - [x] podcasts list
  - [x] podcast page
- [x] og
  - [x] event
  - [x] talk
  - [x] homepage
  - [x] event list
  - [x] "static page"
    - [x] CoC
    - [x] about
  - [x] podcasts list
  - [x] podcast page
- [x] hX
- [x] JSON LD
  - [x] event
  - [x] talk
  - [x] podcast page
- [x] sitemap ⚠️ VERCEL
- [x] robots.txt
- [x] #182 ⏳

</details>

# Page Event

- [x] Page events: venue
- [x] Page events: sponsors
- [x] Page events: partners
- [x] Page events: FAQ
- [x] Page events: after event content
- [x] Hosts into speakers (zod schema string or object string id + enum role)
  - [x] Add to talk page
- [x] Sub Pages
  - [x]  check to remove (we do not remove, sub pages need some data from the event, like published or else)
- [x] Dedicated schedule page
- [x] prospectus
  - [x] Hero button
  - [x] Add to the sponsors block an empty state that is clickable

# Home

- [x] Block what is forkit community + after movie
- [x] Partners

# Pages

- [x] About page
- [ ] #180
- [x] Podcast list
- [x] Podcast details
- [x] Code of conduct style

# Important

🚨 Clean data in MDX

# 😌 Ideas for later

- [ ] #178
- [ ] #177
- [ ] #184

**Comment by yoannfleurydev** [comment]
Closing this issue as v2 is in production. Sub issues are all created
